In [19]:
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [20]:
iris = datasets.load_iris()
x = iris.data
y = iris.target
print(x[0:10])
print(y[0:10])
print(iris.DESCR)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0]
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:  

In [21]:
p = np.random.permutation(len(x))
x = x[p]
y = y[p]
X_train, X_test, Y_train, Y_test = train_test_split(x, y, train_size=0.9)
print(type(Y_train))
print(len(Y_train))
print(len(Y_test))
print(X_train[0:5])

<class 'numpy.ndarray'>
135
15
[[5.8 2.7 4.1 1. ]
 [4.9 2.5 4.5 1.7]
 [6.  2.7 5.1 1.6]
 [5.1 3.8 1.5 0.3]
 [6.3 3.3 6.  2.5]]


In [22]:
std = StandardScaler()
X_train = std.fit_transform(X_train)
X_test = std.transform(X_test)
print(X_train[0:10])
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, Y_train)

[[-0.01161596 -0.8544903   0.2042176  -0.25294802]
 [-1.09726163 -1.32726157  0.4301961   0.66997044]
 [ 0.22963863 -0.8544903   0.76916384  0.53812494]
 [-0.85600704  1.74575169 -1.26464261 -1.17586648]
 [ 0.59152052  0.56382352  1.27761545  1.72473439]
 [-0.97663433  0.56382352 -1.32113724 -1.30771197]
 [-0.01161596 -0.8544903   0.76916384  0.93366142]
 [ 0.59152052  0.80020915  1.05163696  1.59288889]
 [ 0.59152052 -1.32726157  0.65617459  0.40627945]
 [-0.37349785 -1.80003284  0.14772298  0.14258846]]


KNeighborsClassifier()

In [27]:
Y_predict = knn.predict(X_test)
print(Y_predict)
print(Y_test)
print(1 - abs(Y_predict - Y_test).sum() / len(Y_test))

[1 1 1 1 0 1 2 0 1 2 0 2 2 0 1]
[1 1 1 1 0 2 2 0 1 2 0 2 2 0 1]
0.9333333333333333


In [29]:
print(knn.score(X_test, Y_test))

0.9333333333333333
